- name: Install Packages
  hosts: servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Tree
      apt:
        name: tree
        state: present        
