- name: Show Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yml

  tasks:
    - name: Show password
      debug:
        msg: "The password is {{ password }}"
    - name: Show username
      debug:
        msg: "The username is {{ username }}"
    - name: Show API key
      debug:
        msg: "The API key is {{ api_key }}"
